### ISSUE TITLE
What DataSet are we going to use? / What sort of Data?

### ISSUE THREAD

**Issue by NataliaLKB** [MENAccountabilityHack/hackhack#1]
@tsop14 @minaorangina

**Comment by NataliaLKB** [comment]
Ideas Listed:
- Government Spending compared to other countries
- Something on unemployment
- Parliament Data

**Comment by minaorangina** [comment]
[Labour Market Profile in London](https://www.nomisweb.co.uk/reports/lmp/gor/2013265927/report.aspx#tabnrhi)

**Comment by NataliaLKB** [comment]
Decided: https://github.com/MENAccountabilityHack/hackhack/issues/5, so closing
