### ISSUE TITLE
Can't run server :(

### ISSUE THREAD

**Issue by minaorangina** [MENAccountabilityHack/hackhack#17]
`node server.js` gives me:

![screen shot 2015-11-22 at 09 45 41](https://cloud.githubusercontent.com/assets/8915092/11323039/172c1978-90fe-11e5-902e-a3d9702ec1c3.png)

Any ideas?

**Comment by NataliaLKB** [comment]
Upgrade to node 5!

**Comment by minaorangina** [comment]
Installed the version manager thing and it worked :)
